"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
const config_1 = require("prisma/config");
exports.default = (0, config_1.defineConfig)({
    datasource: {
        url: 'file:./prisma/dev.db',
    },
});
//# sourceMappingURL=prisma.config.js.map